//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfLibSharp.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PdfLibSharp.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAACXBIWXMAAA7EAAAOxAGVKw4bAAAgAElEQVR4nO3dfahl5X0v8O/4kp6klxDMCEonyfSelCa3hkxIbKwzYkrpC7WFsWOoXiVFbgK9oDA2NEkpBS+XQkwJI+gfAVOk0nQs1RshDbS3SCMzY9WJVNG+Eacz2kMcmNFKaWXfGD33j71P52Ry3s/ez7PWej4fWMzxzDjrt+ecs5/vel53hCHYmWRfkl1J5pNcNvl41+T335nkkjqlQS+9muTfkjyR5E/nk784kYwq1wRTtaN2AWzaUmP/60muSrK7ajXQjrvnk98RBBgKAaD7lhr8a5PsjwYfajqV5Pokz1SuA7ZNAOig+WTuRPJLST6bceMPdMv1SR6pXQRshwDQLXuS/EaSg7ULAdb1kegJoMcEgMqWPe0fiu596BshgN4SACqZNPyfTvK/YoY+9JkQQC8JAIVp+GFwXk3yk0nO1i4ENkMA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PdfIcon {
            get {
                return ResourceManager.GetString("PdfIcon", resourceCulture);
            }
        }
    }
}
